### PR TITLE
fix: 83 trescanvas component is missing template or render function after 3100

### LINKED ISSUE #83: TresCanvas component is missing template or render function after 3.10.0
### Describe the bug

SSR version of TresCanvas is broken when the project is using `npm` as the package manager.

Screenshot 2024-01-31 at 16 08 39

### Reproduction

https://stackblitz.com/edit/nuxt-starter-hzbvpr?file=nuxt.config.ts

### Steps to reproduce

1. Run `npm install` and `npm run dev`
2. Click on `/page1` link
3. Check console warning. 

### System Info

```shell
System:
    OS: macOS 14.2.1
    CPU: (8) arm64 Apple M1 Pro
    Memory: 89.14 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.14.1 - ~/.nvm/versions/node/v18.14.1/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 9.3.1 - ~/.nvm/versions/node/v18.14.1/bin/npm
  Browsers:
    Brave Browser: 120.1.61.116
    Chrome: 121.0.6167.85
    Firefox: 121.0.1
    Safari: 17.2.1
  npmPackages:
    @tresjs/cientos: ^3.7.0 => 3.7.0 
    @tresjs/nuxt: ^2.1.0 => 2.1.0 
    nuxt: ^3.10.0 => 3.10.0 
    vite-plugin-glsl: ^1.2.1 => 1.2.1 
    vue: ^3.4.15 => 3.4.15 
    vue-router: ^4.2.5 => 4.2.5
```

### Used Package Manager

npm, pnpm

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/Tresjs/tres/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/Tresjs/tres/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://tresjs.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/tresjs/tres/issues) that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

### PR DESCRIPTION
**Pull request by alvarosabu**
This hopefully closes #83 #41 . Thanks @userquin for the fix 🙏🏻 it does work as expected

### CODE REVIEW

File: src/runtime/ServerTresCanvas.vue [hunk 1]
```diff
@@ -1,9 +1,20 @@
 <script setup lang="ts">
+defineOptions({ inheritAttrs: false })
```
Comment (userquin) [inline src/runtime/ServerTresCanvas.vue:2]: Rename the component to `NuxtTresCanvas.vue`

Comment (userquin) [reply src/runtime/ServerTresCanvas.vue:2]: I'm going to add old logic with the span in the server component

File: playground/pages/page1.vue [hunk 2]
```diff
@@ -0,0 +1,24 @@
+<script setup lang="ts">
+// for testing purposes with auto-import disabled
+// import { TresCanvas } from '#components'
+// import { onMounted, useRenderLoop } from '#imports'
+
+const { resume } = useRenderLoop()
```
Comment (userquin) [inline playground/pages/page1.vue:6]: this can be moved inside the `onMounted` hook

Comment (alvarosabu) [reply playground/pages/page1.vue:6]: It can be removed since is a leftover trying to fix the issue you solved.

File: src/module.ts [hunk 3]
```diff
@@ -92,10 +92,28 @@ export default defineNuxtModule<ModuleOptions>({
...
+        }),
+      ])
+    }
+    else {
+      await addComponent({
+        name: 'TresCanvas',
+        filePath: resolver.resolve('./runtime/TresCanvas.client.vue'),
+      })
+    }
+    // await addComponent({
```
Comment (userquin) [inline src/module.ts:113]: remove this

File: src/module.ts [hunk 4]
```diff
@@ -103,6 +92,25 @@ export default defineNuxtModule<ModuleOptions>({
...
+          filePath: resolver.resolve('./runtime/TresCanvas.server.vue'),
+        }),
+      ])
+    }
+    else {
+      await addComponent({
+        name: 'TresCanvas',
+        filePath: resolver.resolve('./runtime/TresCanvas.client.vue'),
+      })
+    }
```
Comment (danielroe) [inline src/module.ts:112]: why do we need if/else?

Comment (userquin) [reply src/module.ts:112]: why registering the server component without ssr enabled?

Comment (danielroe) [reply src/module.ts:112]: It should not do anything in that case, but it will decrease the need for complexity in the module.

Note that `addComponent` is synchronous - no need to await it.

Comment (userquin) [reply src/module.ts]: done
